
server:
  port: 3030

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task-tracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      time-to-live: 60000 #1 minute
  data:
    redis:
      host: 127.0.0.1
      port: 6379